const Gallery = [
  {
    id: 1,
    image: "images/fashion.png",
    // altName: "Portfolio",
    name: "E-commerce",
    url: "https://github.com/Animashaun87/laravel-fashion",
    showOnHome: true,
  },
  {
    id: 2,
    image: "images/pharmacy.png",
    // altName: "Portfolio",
    name: "Pharmacy",
    url: "https://github.com/Animashaun87/pharmacy",
    showOnHome: true,
  },
  // {
  //   id: 3,
  //   image: "images/gallery3.png",
  //   // altName: "Portfolio",
  //   name: "",
  //   url: "",
  //   showOnHome: true,
  // },
  // {
  //   id: 4,
  //   image: "images/gallery4.png",
  //   // altName: "Portfolio",
  //   name: "",
  //   url: "",
  // },
  // {
  //   id: 5,
  //   image: "images/gallery1.png",
  //   altName: "Portfolio",
  //   name: "",
  //   url: "",
  //   showOnHome: true,
  // },
  // {
  //   id: 6,
  //   image: "images/gallery2.png",
  //   altName: "Portfolio",
  //   name: "",
  //   url: "",
  // },
  // {
  //   id: 7,
  //   image: "images/gallery3.png",
  //   altName: "Portfolio",
  //   name: "",
  //   url: "",
  //   showOnHome: true,
  // },
  // {
  //   id: 8,
  //   image: "images/gallery4.png",
  //   altName: "Portfolio",
  //   name: "",
  //   url: "",
  // },
];

export default Gallery;
